name: Nyack Community Garden
markdown: kramdown
url: http://bosborne.github.io
description: Web site for the Nyack Community Garden in Nyack NY USA
port:
destination: site
exclude: ["CNAME", "README.md"]
excerpt_separator: <!--more-->
permalink: /blog/:title

