name: Nyack Community Garden
markdown: kramdown
url: http://bosborne.github.io
description: Web site for the Nyack Community Garden in Nyack NY USA
port:
destination: _site
exclude: ["CNAME", "README.md"]
excerpt_separator: <!--more-->
permalink: /blog/:title
google_analytics: UA-96599061-1

